name: Alpha Pipeline
on:
  push:
    branches:
      - 'alpha*'
    paths:
      - 'src/**'
env:
  nuget-username: chrisxpr
  src-dir: ./src/code
  build-environment: dev
  coverage-threshold: 90
  repo-organisation: architected
  team-pat: ${{ secrets.TEAM_PAT}}
concurrency: alpha-${{ github.ref}}
jobs:
  dotnetBuild:
    name: Build and Test
    runs-on: ubuntu-latest
    environment: dev
    timeout-minutes: 20
    steps:
      - name: Checkout action
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      
      - name: buildAndTest
        uses: devperimental/composite-action-library/dotnet-build-and-test@v1
        with:
          nuget-username: ${{ env.nuget-username }}
          src-dir: ${{ env.src-dir }}
          build-environment: ${{ env.build-environment }}
          coverage-threshold: ${{ env.coverage-threshold }}
          repo-organisation: ${{ env.repo-organisation }}
          team-pat: ${{ env.team-pat }}

  pushPackages:
    name: Push Packages
    runs-on: ubuntu-latest
    needs: dotnetBuild
    environment: dev
    timeout-minutes: 20
    steps:
      - name: Checkout action
        uses: actions/checkout@v3
        with:
          persist-credentials: false
   
      - uses: devperimental/composite-action-library/nuget-package@v1
        with:
          nuget-username: ${{ env.nuget-username }}
          src-dir: ${{ env.src-dir }}
          repo-organisation: ${{ env.repo-organisation }}
          team-pat: ${{ env.team-pat }}
