name: Main Pipeline
on:
  push:
    branches:
      - 'main'
env:
  nuget-username: devperimental
  src-dir: ./src/code
  build-environment: dev
  coverage-threshold: 90
  repo-organisation: architected
  team-pat: ${{ secrets.TEAM_PAT}}
concurrency: main-${{ github.ref}}
jobs:
  dotnetBuild:
    name: Build and Test solution
    runs-on: ubuntu-latest
    environment: dev
    timeout-minutes: 20
    steps:
      - name: Checkout action
        uses: actions/checkout@v3
        with:
          persist-credentials: false
    
      - name: buildAndTest
        uses: dotnet-build-and-test
        with:
          repository: devperimental/composite-action-library
          nuget-username: ${{ env.nuget-username }}
          src-dir: ${{ env.src-dir }}
          build-environment: ${{ env.build-environment }}
          coverage-threshold: ${{ env.coverage-threshold }}
          repo-organisation: ${{ env.repo-organisation }}
          team-pat: ${{ secrets.TEAM_PAT}}
  pushPackages:
    name: Push Packages
    needs: dotnetBuild
    runs-on: ubuntu-latest
    environment: dev
    timeout-minutes: 20
    steps:
      - name: Checkout action
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: nuget-package
        with:
          repository: devperimental/composite-action-library
          nuget-username: ${{ env.nuget-username }}
          src-dir: ${{ env.src-dir }}
          repo-organisation: ${{ env.repo-organisation }}
          team-pat: ${{ secrets.TEAM_PAT}}
