name: Main Pipeline
on:
  push:
    branches:
      - 'main'
env:
  nuget-username: devperimental
  src-dir: ./src/code
  build-environment: dev
  coverage-threshold: 90
  repo-organisation: architected
  team-pat: ${{ secrets.TEAM_PAT}}
concurrency: main-${{ github.ref}}
jobs:
  dotnetBuild:
    name: Build and Test solution
    runs-on: ubuntu-latest
    environment: dev
    timeout-minutes: 20
    steps:
      - name: Checkout action
        uses: actions/checkout@v3
        with:
          persist-credentials: false
    
  pushPackages:
    name: Push Packages
    needs: dotnetBuild
    runs-on: ubuntu-latest
    environment: dev
    timeout-minutes: 20
    steps:
      - name: Checkout action
        uses: actions/checkout@v3
        with:
          persist-credentials: false

